version: '3.7'
services:
    aws:
        image: organs/awscli
        environment:
            AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
            AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
            AWS_REGION: us-east-1
            AWS_DEFAULT_REGION: us-east-1
        env_file: .env
        volumes:
            - .:/app
        working_dir: /app
    terraform:
        build:
            context: .
            dockerfile: terraform.Dockerfile
        environment:
            AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
            AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
            AWS_REGION: us-east-1
            AWS_DEFAULT_REGION: us-east-1
        volumes:
            - .:/app
        working_dir: /app         
    website:
        build:
            context: .
        ports:
            - 8080:8080