version: '3.7'
services:
    terraform:
        build:
            context: .
        dockerfile: terraform.dockerfile
        environment:
            AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
            AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
            AWS_REGION: us-east-1
            AWS_DEFAULT_REGION: us-east-1
          volumes:
            - .:/app
          working_dir: /app
    website:
        build:
            context: .
        ports:
            - 8080:8080